"""empty message

Revision ID: 642037447a02
Revises: 04790b0b3961
Create Date: 2021-02-12 17:37:36.987505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642037447a02'
down_revision = '04790b0b3961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'image')
    # ### end Alembic commands ###
