"""empty message

Revision ID: 6bc5ecd70268
Revises: 65f5f5c644e1
Create Date: 2021-02-09 15:09:42.181421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc5ecd70268'
down_revision = '65f5f5c644e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
