"""empty message

Revision ID: 6ed0bd0d3276
Revises: 4c4247301d7e
Create Date: 2021-02-09 18:54:16.565862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed0bd0d3276'
down_revision = '4c4247301d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ref__payment__method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref__payment__method',
    sa.Column('payment_method_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('payment_method_description', sa.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('payment_method_code')
    )
    # ### end Alembic commands ###
