"""empty message

Revision ID: a9c2322418d0
Revises: 6bc5ecd70268
Create Date: 2021-02-09 15:19:25.945913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c2322418d0'
down_revision = '6bc5ecd70268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
